# NewDayNotifier config
# by @kararasenok_gd

settings:
  # Where new day should be displayed
  display: "actionbar" # options: actionbar, chat, title

  # Name of the world where the plugin should track days
  world: "world"

  # Play sound when a new day starts
  sound:
    enabled: true
    id: "entity.player.levelup" # Sound ID. You can test it by using command /playsound minecraft:<sound id> master @p

messages:
  # Messages to send when a new day comes. %day% = current day
  actionbar:
    text: "§eDay §6%day%" # Text for action bar display

  chat:
    text: "§eDay §6%day%" # Text for chat display

  title:
    text: "New day!"       # Main title text
    subtext:
      enabled: true         # Show subtext under main title
      text: "Current day: %day%" # Subtext content